DROP DATABASE IF EXISTS plantsdb;
CREATE DATABASE plantsdb;
CREATE USER postgres WITH ENCRYPTED PASSWORD 'postgres';
GRANT ALL PRIVILEGES ON DATABASE plantsdb TO postgres;
ALTER USER postgres CREATEDB;
ALTER USER postgres WITH SUPERUSER;
