"""add the TodoList model and associate foreign key

Revision ID: e06454421031
Revises:
Create Date: 2026-09-18 10:26:45.827187

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "e06454421031"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "todolists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute("UPDATE todos SET completed = FALSE WHERE completed IS NULL")
    with op.batch_alter_table("todos", schema=None) as batch_op:
        batch_op.add_column(sa.Column("list_id", sa.Integer(), nullable=True))
        batch_op.alter_column("completed", existing_type=sa.BOOLEAN(), nullable=False)
        batch_op.create_foreign_key(None, "todolists", ["list_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("todos", schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.alter_column("completed", existing_type=sa.BOOLEAN(), nullable=True)
        batch_op.drop_column("list_id")

    op.drop_table("todolists")
    # ### end Alembic commands ###
